### ISSUE TITLE
When u open carhud but u not can't close it

### ISSUE THREAD

**Issue by FLTumble** [EntityEvolution/ev-carhud#3]
So i found this issue last night when u open carhud and change what u want then u save, and try close it whit a "X" on up corner whitch dosen't work i need a closeit diffrent way ehter i restart script or f8 console and write command /carhud then u need a leave a car then that ui not enymore shown our screen. Im Not sure if this aldready fixed or not..

**Comment by BombayV** [comment]
Fixed on discord.
